### ISSUE TITLE
Cachelösning 

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se#11]
@khromov kanske kan kolla om det ens behövs?

**Comment by PontusTideman** [comment]
Vad har vi kört med innan? Är det tänkt att vi ska köra med Varnish, Memcache eller någon annan lösning?

**Comment by marcustisater** [comment]
Vi körde Redis men jag tror vi bör gå en annan väg. Jag är osäker om det ens behövs.

**Comment by PontusTideman** [comment]
Varnish är ju relativt lätt att sätta upp beroende på vad för hosting vi har. :)

**Comment by marcustisater** [comment]
Det får nog bli redis som är installerat idag på Seravo

**Comment by khromov** [comment]
@marcustisater Fast är det Object Cache eller Page cache de har? Om vi behöver köra nån plugg för statisk cache så föreslår jag Cache Enabler, den är väldigt clean och o-bloatad: https://wordpress.org/plugins/cache-enabler/

**Comment by marcustisater** [comment]
Object cache tror jag men är inte Nginx page cachning? Jag har inte så bra koll så ni får nog fatta något beslut. Jag håller med om att en statisk cache räcker gott och väl.

Vad jag läser från deras spec som är pre-installed på servern är: Nginx cachning, PHP7, Redis och PageSpeed.

**Comment by khromov** [comment]
@marcustisater Jo, om de har page cached med Nignx så duger det gott oåt oss.
