### ISSUE TITLE
Installera piwik

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se#14]
https://piwik.org/

**Comment by marcustisater** [comment]
@kodapaio nämnde

> Du kan köpa hostingplats hos PIWIK, men PIWIK kan du hosta själv också på egen VPS t.ex.

**Comment by khromov** [comment]
Föreslår att vi för enkelhetens skull använder min Piwik-instans så länge. Finns behovet så kan vi byta längre fram. Vi kan också installera WP-Piwik på WPSV.se och offentliggöra statistiken, som vi diskuterat: https://wordpress.org/plugins/wp-piwik/

Man behöver en API-nyckel för att få ut statistiken, skickar den till dig via PM.

**Comment by khromov** [comment]
Har lagt in pluggen WP-Piwik som en Composer dependency nu.

**Comment by khromov** [comment]
Färdigt, statistiken finns i WP-admin.
