### ISSUE TITLE
Skisser

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se#16]
Ladda upp skisser samt sitemap etc.

**Comment by khromov** [comment]
@marcustisater Visst hade du bilder? Om inte så kan jag ladda upp dem.

**Comment by marcustisater** [comment]
Yup men var ska vi ladda upp de?

**Comment by khromov** [comment]
Det går att ladda upp dem här i issuen tror jag.

**Comment by marcustisater** [comment]
funderar på om kan ladda upp de på Wiki https://github.com/wpsvse/wpsv.se/wiki

**Comment by marcustisater** [comment]
jag laddar upp skisserna ikväll, kollar vad som är lämpligast.

**Comment by marcustisater** [comment]
![img_20161220_205251](https://cloud.githubusercontent.com/assets/2952332/21396817/c1fb99fc-c7a1-11e6-9313-6888e56cf7f7.jpg)
![img_20161220_205238](https://cloud.githubusercontent.com/assets/2952332/21396816/c1fa6e60-c7a1-11e6-91d4-944a43f0e4bc.jpg)
![img_20161220_205245](https://cloud.githubusercontent.com/assets/2952332/21396818/c1fc8f60-c7a1-11e6-824a-2a2ad9157909.jpg)
![img_20161220_210844](https://cloud.githubusercontent.com/assets/2952332/21396819/c1fce618-c7a1-11e6-8ebe-a642e2f0202e.jpg)

**Comment by marcustisater** [comment]
det ligger under wiki också https://github.com/wpsvse/wpsv.se/wiki/Skisser
